### ISSUE TITLE
Opening a UI component shows nothing

### ISSUE THREAD

**Issue by Mikadifo** [MarsX-dev/floatui#11]
Every time I open a component to see the examples and code I can't see anything, I remember that a couple of days ago it was working fine. I tried on 3 browsers, Brave, Safari and Firefox, all of them I get the same problem, I also tried on my phone.

<img width="1438" alt="Screenshot 2023-03-28 at 10 10 06 PM" src="https://user-images.githubusercontent.com/51935560/228408276-d8ed1654-5eea-4944-a663-85f16f0a3b3c.png">

**Comment by EL-MEHDI-ESSAADI** [comment]
Same here

**Comment by Dev-Ahmadubah** [comment]
Also the same here
![Screenshot (458)](https://user-images.githubusercontent.com/60859825/228531644-8fade0b6-0429-410e-ad70-c8b1997118bb.png)

**Comment by priyanka-mahour** [comment]
none of the Marketing components are coming but it's working fine for Application UI components

<img width="1565" alt="image" src="https://user-images.githubusercontent.com/43825112/228532476-b60a9b80-efb2-43cf-912b-97b4baf618e3.png">

**Comment by Mikadifo** [comment]
Yeah, it does work fine now.

**Comment by sidiDev** [comment]
> Yeah, it does work fine now.

Thank you Mikadifo, the problem was caused of the the JS script for generating the components, sometimes doesn't generate all the components quickly, I think I will build the script with Rust, soon.
