### ISSUE TITLE
Footer isn't fixed at the bottom

### ISSUE THREAD

**Issue by priyanka-mahour** [MarsX-dev/floatui#12]
<img width="1676" alt="image" src="https://user-images.githubusercontent.com/43825112/228533306-c3d0d607-3ff5-461b-a00c-1f22896c1360.png">

**Comment by Samit-prsl** [comment]
Hey I can fix this

**Comment by sidiDev** [comment]
Hi Thanks for this feedback, basically we know that before, and I don't think it's a problem we can worry about.
