### ISSUE TITLE
Could not clone the repository

### ISSUE THREAD

**Issue by Samit-prsl** [MarsX-dev/floatui#13]
invalid index-pack output
Unlink of file 'floatui/.git/objects/pack/tmp_pack_ahDJyT' failed.

*this error is being shown after writing the git clone command in the terminal/powershell*.

**Comment by sidiDev** [comment]
> invalid index-pack output Unlink of file 'floatui/.git/objects/pack/tmp_pack_ahDJyT' failed.
> 
> _this error is being shown after writing the git clone command in the terminal/powershell_.

Hi Samit! I don't think the problem caused of Float UI repo.

Checkout this it's may help you: https://stackoverflow.com/questions/4389833/unlink-of-file-failed-should-i-try-again
