### ISSUE TITLE
Components are not tested 

### ISSUE THREAD

**Issue by dubar-jeremy** [MarsX-dev/floatui#15]
Hi,

Thanks for sharing your components and themes for free.

I was thinking about testing some of your components and wanted to check with you first: Is there a reason why components haven't been tested yet? Is it because there hasn't been enough time or do you feel it's not necessary for this project?

**Comment by sidiDev** [comment]
Hi Dubar! What do you mean by tested? Our components are well designed and built, and we tested it many times, but nothing is perfect 100%, and we are trying our best to do a good work.

**Comment by jalalbmnf** [comment]
Hi @sidiDev maybe he means,writing component testing

**Comment by dubar-jeremy** [comment]
exactly @jalalbmnf
