### ISSUE TITLE
Empty folder with submodule icon in FloatUI repository

### ISSUE THREAD

**Issue by chakkyy** [MarsX-dev/floatui#2]
### Description
The templates/mailgo folder in the FloatUI repository contains a submodule icon but is empty. There is no .gitmodules file in the repository to initialize the submodule. As a result, the contents of the folder cannot be accessed.

### Steps to Reproduce
Fork or clone the FloatUI repository from https://github.com/MarsX-dev/floatui
Navigate to the templates/mailgo folder
Observe that the folder is empty and the submodule icon is present

### Expected Behavior
The templates/mailgo folder should contain files relevant to the FloatUI project.

### Actual Behavior
The templates/mailgo folder is empty.

### Environment
Operating system: macOS Ventura 13.2.1
Git version 2.37.0

### Attempts
A commit message has been found which confirms that the templates/mailgo folder is a submodule in the FloatUI repository. The commit message states that the submodule was added in commit ce7759e with the commit hash b31757 as the reference for the submodule.

`git submodule init` and `git submodule update` have been executed, but it seems that the submodule reference is not being properly initialized or updated in the local copy of the repository. Further investigation may be needed to determine the cause of the issue.

### Error Messages or Logs
The following error message was encountered when executing the git submodule init command:
`fatal: No se encontró url para la ruta del submódulo 'templates/mailgo' en .gitmodules`

This translates to `fatal: No URL found for submodule path 'templates/mailgo' in .gitmodules`

This error message suggests that the submodule reference for templates/mailgo may not be properly configured in the .gitmodules file.

### References
There are no additional references.

**Comment by sidiDev** [comment]
Hi @chakkyy Thank you for reporting this issue, We just fixed it.
