### ISSUE TITLE
Component page Sidebar (React) RTL error

### ISSUE THREAD

**Issue by NohaPepeep** [MarsX-dev/floatui#24]
Hello FloatUI,

There is an error occurs when switching the Sidebar components page from LTR to RTL.
https://www.floatui.com/components/sidebars

The details of the error:
Application error: a client-side exception has occurred (see the browser console for more information).

**Comment by sidiDev** [comment]
@NohaPepeep Hi Nuha! Thanks for contributing, I just fixed it, you can check it out.
