### ISSUE TITLE
Typo in "mission" instead of "mession"

### ISSUE THREAD

**Issue by Dev-Ahmadubah** [MarsX-dev/floatui#25]
There is a typing error in the project's website. The word "mession" is used instead of "mission".

![Screenshot (477)](https://github.com/MarsX-dev/floatui/assets/60859825/5109fe54-e94b-4df8-b5a0-992cd9fa0532)

**Comment by sidiDev** [comment]
@Dev-Ahmadubah Thanks for this, will fix it.

**Comment by Dev-Ahmadubah** [comment]
I can work on it

**Comment by Mikadifo** [comment]
Looks fixed in the new version!
