### ISSUE TITLE
floatui.com: whenever I open any component's page, it redirects me to the homepage

### ISSUE THREAD

**Issue by Lippiece** [MarsX-dev/floatui#3]
https://user-images.githubusercontent.com/47634624/227637387-551c98e9-1a52-4141-979c-c7ae5a37d023.mp4

**Comment by Youssef535** [comment]
Hello i think it's from your browser please try to delete your cookies and try again or it's from the browser version.

**Comment by sidiDev** [comment]
Hi @Lippiece pease check it out again, we just fixed it.
