### ISSUE TITLE
FloatUI Vue

### ISSUE THREAD

**Issue by ijkml** [MarsX-dev/floatui#4]
Hi :wave:, read that you want to add vue components. It's something (I think) I can help with. Please can you provide guidelines? Is there any template or pattern to follow?

**Comment by sidiDev** [comment]
Hi @ijkml That's awesome, Yes we have, join our Discord usning this link so I can add you to our channel for Float UI:
https://discord.gg/dFtFcdrNqv

You can also read this guidelines: https://github.com/MarsX-dev/floatui/blob/main/CONTRIBUTING.md

**Comment by ijkml** [comment]
Thank you, I have done that.
