### ISSUE TITLE
Homepage 'Get Started' Button Does Not Navigate to Components Page

### ISSUE THREAD

**Issue by shaikahmadnawaz** [MarsX-dev/floatui#46]
**Steps to Reproduce:**
1. Visit the homepage of floatui.com.
2. Locate the 'Get Started' button.
3. Click on the 'Get Started' button.

![Screenshot (1382)](https://github.com/MarsX-dev/floatui/assets/96189881/2b9a8ea8-7658-4a9c-9e9c-d7ea3aeadd98)

**Expected Behavior:**
After clicking on the 'Get Started' button, the user should be redirected to the following URL: [https://www.floatui.com/components](https://www.floatui.com/components).

**Actual Behavior:**
After clicking on the 'Get Started' button, there is no redirection, and the user remains on the homepage.

**Pull Request Offer:**
I am ready and willing to contribute a pull request to address this issue. If there are any specific guidelines or preferences for contributing to the project, please provide them.

**Comment by sidiDev** [comment]
@shaikahmadnawaz Thanks for reporting, you can fix it and send a pull request. Go for it dude.

**Comment by shaikahmadnawaz** [comment]
> @shaikahmadnawaz Thanks for reporting, you can fix it and send a pull request. Go for it dude.

Thank you @sidiDev, raised PR #47.

**Comment by sidiDev** [comment]
> > @shaikahmadnawaz Thanks for reporting, you can fix it and send a pull request. Go for it dude.
> 
> Thank you @sidiDev, raised PR #47.

@shaikahmadnawaz Great thing, just merged your PR #47
