### ISSUE TITLE
Homepage 'Get Started' Button Does Not Navigate to Components Page in CTA section

### ISSUE THREAD

**Issue by shaikahmadnawaz** [MarsX-dev/floatui#48]
@sidiDev, I just found another similar navigation issue,

![Screenshot (1384)](https://github.com/MarsX-dev/floatui/assets/96189881/a8e494c8-833b-4221-964f-be4ac7992134)

**Steps to Reproduce:**
1. Visit the homepage of floatui.com.
2. Locate the 'Get Started' button.
3. Click on the 'Get Started' button.

**Expected Behavior:**
After clicking on the 'Get Started' button, the user should be redirected to the following URL: [https://www.floatui.com/components](https://www.floatui.com/components).

**Actual Behavior:**
After clicking on the 'Get Started' button, there is no redirection, and the user remains on the homepage.

**Pull Request Offer:**
I am ready and willing to contribute a pull request to address this issue. If there are any specific guidelines or preferences for contributing to the project, please provide them.

**Comment by sidiDev** [comment]
Cool, I really appreciate your reporting for issues like this, fix it and I will merge right away.

**Comment by shaikahmadnawaz** [comment]
> Cool, I really appreciate your reporting for issues like this, fix it and I will merge right away.

Thanks for your kind words! @sidiDev

**Comment by sidiDev** [comment]
Just merged it #49
