### ISSUE TITLE
Typo on floatui.com Homepage

### ISSUE THREAD

**Issue by Logicless-Coder** [MarsX-dev/floatui#5]
There is a typo on the [floatui.com](floatui.com)'s homepage. 
If you scroll down a bit to features to see the demonstration image of Modern UI Components (LTR/RTL feature) you will find "Software" is spelled as "Softaware". 

![Screenshot_2023-03-26-19-58-18_1920x1080](https://user-images.githubusercontent.com/59042344/227782664-b9ee62e9-fc4a-4a98-a9da-b0954f53d078.png)

**Comment by sidiDev** [comment]
@Logicless-Coder HI there! Thank you so much for this contribute, we just fixed it.
