### ISSUE TITLE
bug: Navbar HTML code missing

### ISSUE THREAD

**Issue by ZeeshanSultan** [MarsX-dev/floatui#55]
https://floatui.com/components/navbars

only react code is available for all navbars? upon clicking any other code button the UI gets stuck on the "In progress..." screen

<img width="1129" alt="Screenshot 2024-01-04 at 11 09 17 AM" src="https://github.com/MarsX-dev/floatui/assets/8667667/10f4558d-5ec5-4b19-9610-a75c1c093f37">

**Comment by bmuzuraimov** [comment]
Same problem with Vue.js sidebars

**Comment by tristonarmstrong** [comment]
> https://floatui.com/components/navbars
> 
> only react code is available for all navbars? upon clicking any other code button the UI gets stuck on the "In progress..." screen
> 
> <img alt="Screenshot 2024-01-04 at 11 09 17 AM" width="1129" src="https://private-user-images.githubusercontent.com/8667667/294100071-10f4558d-5ec5-4b19-9610-a75c1c093f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjA3MzgsIm5iZiI6MTcxMTg2MDQzOCwicGF0aCI6Ii84NjY3NjY3LzI5NDEwMDA3MS0xMGY0NTU4ZC01ZWM1LTRiMTktOTYxMC1hNzVjMWMwOTNmMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMDQ0NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3YmYxOGI5MTk5NDc4MjYwNTAxYTBiMzU1ZDZkY2YzZDM1NTk1MjFlZDNlYTFkMjJmZmY5NGRhMzY5MzVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3yd5koPaNOJSPMPQShpzTa0QKZB3sP0zvx4GdtQH85M">

Looking through the code, `In Progress` seems to denote that the work is not yet finished for this particular code example. I do see how it can be confused for a `Loading In Progress` indicator and how it could seem to be "stuck". 

This isnt technically an issue, just incomplete example set.

**Comment by sidiDev** [comment]
> > https://floatui.com/components/navbars
> > only react code is available for all navbars? upon clicking any other code button the UI gets stuck on the "In progress..." screen
> > <img alt="Screenshot 2024-01-04 at 11 09 17 AM" width="1129" src="https://private-user-images.githubusercontent.com/8667667/294100071-10f4558d-5ec5-4b19-9610-a75c1c093f37.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE4NjA3MzgsIm5iZiI6MTcxMTg2MDQzOCwicGF0aCI6Ii84NjY3NjY3LzI5NDEwMDA3MS0xMGY0NTU4ZC01ZWM1LTRiMTktOTYxMC1hNzVjMWMwOTNmMzcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMzMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMzFUMDQ0NzE4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDI3YmYxOGI5MTk5NDc4MjYwNTAxYTBiMzU1ZDZkY2YzZDM1NTk1MjFlZDNlYTFkMjJmZmY5NGRhMzY5MzVlNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.3yd5koPaNOJSPMPQShpzTa0QKZB3sP0zvx4GdtQH85M">
> 
> Looking through the code, `In Progress` seems to denote that the work is not yet finished for this particular code example. I do see how it can be confused for a `Loading In Progress` indicator and how it could seem to be "stuck".
> 
> This isnt technically an issue, just incomplete example set. Maybe this should be relabled to "Work In Progress..." or something

Correct 100%, thanks for your comment.
